## Overview {.tabset .tabset-fade}

Experiment summary

```{r global_options, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.height=7, fig.width=7)
library(ggplot2)
library(reshape2)
library(irene)
library(DT)
Sys.setlocale("LC_NUMERIC","C")
options(stringsAsFactors=FALSE)
mk=c("H3K27ac","H3K27me3","H3K36me3","H3K4me1","H3K4me3","H3K9me3")
nm=c("CLL","Glioma","CRC","B-ALL","AML","CLL-2","MCL","MM","PTC")
```

### Data
Data sources

```{r}
conf=read.table('res/ChIPdesign.txt',sep='\t',stringsAsFactors=FALSE,col.names=c('experiment','factor','condition','ipReads','ctReads','peaks'))
datatable(conf,rownames=FALSE,filter="top",options=list(pageLength=20,scrollX=TRUE,autoWidth=TRUE))
```

### Benchmark
__AUCs of different histone markrs__

```{r}
auc_marks=data.frame(lapply(1:9,function(i){
unlist(lapply(1:6,function(j){
get.auc(get.rank(markers[[i]],get.generank(marks[[i]][[j]])))
}))
}),row.names=mk)
colnames(auc_marks)=nm
#auc_marks=rbind(auc_marks, dPC1=getAUCs(enh))
ggplot(melt(as.matrix(auc_marks)), aes(x=Var2, y=value, colour=Var1, shape=Var1))+geom_point(size=4)+labs(x="Test cases",y="AUCs")
```

__AUCs of randomized promoter-enhancer interaction network using PC1__

```{r}
df=do.call(rbind, lapply(1:9,function(i){
quantile(unlist(lapply(rewired[[i]],function(d){
get.auc(get.rank(markers[[i]], d))
})))
}))
df=data.frame(df[,c(2,4)], type=1:9, prom=getAUCs(prom), enh=getAUCs(enh))
names(df)[1:2]=c('q1','q3')
dname=function(i) nm[i]
ggplot(df,aes(type))+geom_ribbon(aes(ymin=q1,ymax=q3),fill="grey70")+geom_line(aes(y=enh),color="red")+geom_line(aes(y=prom),color="red",linetype="dashed")+ scale_x_continuous(breaks=1:9,label=dname)+labs(x="",y="AUC")
```

