## title {.tabset .tabset-fade}
content above tabbed region.

```{r global_options, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.height=7, fig.width=7)
library(ggplot2)
library(reshape2)
library(irene)
library(DT)
Sys.setlocale("LC_NUMERIC","C")
options(stringsAsFactors=FALSE)
data(markers)
load('res/res.rda')
mk=c("H3K27ac","H3K27me3","H3K36me3","H3K4me1","H3K4me3","H3K9me3")
nm=c("CLL","Glioma","CRC","B-ALL","AML","CLL-2","MCL","MM","PTC")
goi=list(c('PAX5'))
i=1
conf=read.table('res/ChIPdesign.txt',sep='\t',stringsAsFactors=FALSE,col.names=c('experiment','factor','condition','ipReads','ctReads','peaks'))
conf=conf[conf$experiment==i & conf$factor!="H3K9ac",]
dat=res[[i]]
opt=list(pageLength=5,scrollX=TRUE,order=list(list(1,'desc')),autoWidth=TRUE)
newopt <- function(d,...) {d$dd=1;d}
read.txt <- function(f){
    txt=strsplit(readLines(f),"\t")
    v=lapply(txt,function(d) d[3:length(d)])
    names(v)=lapply(txt,function(d) d[1])
    v
}
getAUC <- function(f,d) 
datatable(data.frame(AUC=unlist(lapply(read.txt(f),function(a) sprintf('%.3f', get.auc(get.rank(a, d[[i]])))))),rownames=TRUE,filter="top",options=opt)
getAUCs <- function(d) 
unlist(lapply(1:7,function(i) get.auc(get.rank(markers[[i]], get.generank(d[[i]])))))
getAUCmat <- function(d) 
lapply(1:7,function(i){unlist(lapply(1:6,function(j) get.auc(get.rank(markers[[i]], get.generank(d[[i]][[j]])))))})
```

### PC
__PC composition__
```{r}
df=data.frame(melt(prcomp(dat$Dobs)$rotation),rep(levels(as.factor(conf$factor)),ncol(dat$Dobs)))
colnames(df)=c("id","PC","Loadings","Mark")
ggplot(df,aes(x=Mark,y=Loadings,fill=Mark))+geom_bar(stat='identity')+facet_grid(PC~.)+coord_flip()+theme(legend.position="none",axis.text.x=element_text(angle=90,vjust=0.5))
```

__PC variance__
```{r}
df=melt(dat$proj)
df=df[!is.na(df[,3]),]
df=df[df[,1]=="percent_var",2:3]
colnames(df)=c("PC","var")
df$PC=as.character(df$PC)
ggplot(df,aes(x=PC,y=var,fill=PC))+geom_bar(stat='identity')+labs(x="PC",y="Variance")+scale_y_continuous(labels=scales::percent)+theme(legend.position="none")
```

### Rank
```{r}
datatable(data.frame(Rank=rank[[i]]),rownames=TRUE,filter="top",options=opt)
```

### ECDF
```{r}
df=rbind(data.frame(get.rankid(markers[[i]], enh[[i]]),list='Irene'), data.frame(get.rankid(markers[[i]], prom[[i]]),list='Promoter'))
ggplot(df,aes(rank,colour=list))+stat_ecdf(pad=TRUE)+labs(x="Rank",y="ECDF")
datatable(df,rownames=FALSE,filter="top",options=list(pageLength=5,scrollX=TRUE,autoWidth=TRUE))
```

### AUC
enh to prom
```{r}
prom_auc=do.call(cbind,lapply(1:6,function(k){
getAUCs(lapply(1:9,function(i){
j=get.geneid(res[[i]]$bed[,4])
gsub("_\\d+", "", res[[i]]$bed[j,4][order(abs(res[[i]]$Dobs[j,k]),decreasing=TRUE)])
}))
}))
```

### Enrichment
__Tissue specificity__
```{r}
getAUC('res/ARCHS4_Tissues.txt',enh)
```

__KEGG__
```{r}
getAUC('res/KEGG_2016.txt',enh)
```

__WikiPathways__
```{r}
getAUC('res/WikiPathways_2016.txt',enh)
```

### Data validity

__Distribution densities__

```{r, eval=FALSE}
library(quantro)
matdensity(data,mark,main=s,xlab="",ylab="")
legend('topright',levels(mark),col=RColorBrewer::brewer.pal(8,"Dark2"),lty=1,lwd=3)
```

__Correlations between epigenetic marks__

Correlations between epigenetic marks in each group

```{r, eval=FALSE}
m=matrix(NA,6,6)
for(i in 1:6){for(j in 1:6){m[i,j]=cor(res[[1]]$Dobs[,i],res[[1]]$Dobs[,j])}}
ggplot(m,aes(cell,Var1,fill=value))+geom_tile(colour="white")+
  facet_grid(.~Var2)+scale_fill_gradient2(low="blue",high="red") +
  theme(axis.text.x=element_text(angle=90,size=7,vjust=0.5))+labs(x="",y="")
```

### Genes of interests
```{r}
datatable(data.frame(Rank=rank[[i]]),rownames=TRUE,filter="top",options=opt)
```


##
content below tabbed region
